apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudops-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudops-backend
  template:
    metadata:
      labels:
        app: cloudops-backend
    spec:
      containers:
        - name: backend
          image: cloudops-backend:ci
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5